
import RestFood.RestDrinks.*;
import RestFood.RestDrinks.DrinkType.*;
import java.util.EnumSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anton
 */
public class DrinksForm extends javax.swing.JPanel {

    /**
     * Creates new form DrinksForm
     */
    DefaultListModel chooseModel = new DefaultListModel();
    DefaultListModel teaTypeModel = new DefaultListModel();
    DefaultListModel juiceTypeModel = new DefaultListModel();
    DefaultListModel coffeeTypeModel = new DefaultListModel();
    DefaultComboBoxModel sizeModel = new DefaultComboBoxModel();
    DefaultListModel listOrderModel;
    DrinkList DrinkChoosed = DrinkList.espresso;
    public DrinksForm(DefaultListModel listOrderModel) {
        initComponents();
        initModels();
        initComp();
        this.listOrderModel = listOrderModel;
    }
    public void initComp()
    {
        listType.setEnabled(false);
        cbListSize.setEnabled(false);
        listDrinkList.setSelectedIndex(0);
    }
    public void initModels()
    {
        EnumSet.allOf(DrinkList.class)
                .forEach(drink -> chooseModel.addElement(drink));
        listDrinkList.setModel(chooseModel);
        EnumSet.allOf(TeaType.class)
                .forEach(type -> teaTypeModel.addElement(type));
        EnumSet.allOf(JuiceType.class)
                .forEach(type -> juiceTypeModel.addElement(type));
        EnumSet.allOf(DrinkSize.class)
                .forEach(size -> sizeModel.addElement(size));
        cbListSize.setModel(sizeModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listDrinkList = new javax.swing.JList<>();
        btnChoose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listType = new javax.swing.JList<>();
        cbListSize = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbCaffeine = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnAddDrink = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(450, 315));

        jScrollPane1.setViewportView(listDrinkList);

        btnChoose.setText("Choose Drink");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listType);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("DrinkSize:");

        cbCaffeine.setText("No");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Caffeine:");

        btnAddDrink.setText("Add drink");
        btnAddDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCaffeine)
                                    .addComponent(cbListSize, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAddDrink, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbListSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCaffeine)
                            .addComponent(jLabel2))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChoose)
                    .addComponent(btnAddDrink))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        // TODO add your handling code here:
        DrinkChoosed = (DrinkList)chooseModel.get(listDrinkList.getSelectedIndex());
        if(DrinkChoosed.getDrinkType() == DrinkType.coffee)
        {
            listType.setModel(coffeeTypeModel);
            listType.setEnabled(false);
            if(DrinkChoosed.getName() == "Espresso") {
            cbListSize.setEnabled(false);
            cbListSize.setSelectedIndex(0); 
            } else { cbListSize.setEnabled(true); }
            cbCaffeine.setEnabled(true);
        }else if(DrinkChoosed.getDrinkType() == DrinkType.tea)
        {
            listType.setModel(teaTypeModel);
            listType.setEnabled(true);
            listType.setSelectedIndex(0);
            cbListSize.setEnabled(false);
            cbCaffeine.setEnabled(false);
            cbCaffeine.setSelected(false);
        }else if(DrinkChoosed.getDrinkType() == DrinkType.juice)
        {
            listType.setModel(juiceTypeModel);
            listType.setEnabled(true);
            listType.setSelectedIndex(0);
            cbListSize.setEnabled(false);
            cbCaffeine.setEnabled(false);
            cbCaffeine.setSelected(false);
        }
    }//GEN-LAST:event_btnChooseActionPerformed

    private void btnAddDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrinkActionPerformed
        // TODO add your handling code here:
        Drinks createdDrink;
        Object concreteDrinkType = null;
        if(!listType.isSelectionEmpty()){
            concreteDrinkType = listType.getModel().getElementAt(listType.getSelectedIndex());
        }
        DrinkSize concreteDrinkSize = (DrinkSize)sizeModel.getElementAt(cbListSize.getSelectedIndex());
        boolean isCaffeine = cbCaffeine.isSelected();
        createdDrink = DrinkMaker.DrinkCreate(DrinkChoosed, concreteDrinkType, concreteDrinkSize, isCaffeine);
        JOptionPane.showMessageDialog(null, createdDrink.getDescribe());
        listOrderModel.addElement(createdDrink);
    }//GEN-LAST:event_btnAddDrinkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDrink;
    private javax.swing.JButton btnChoose;
    private javax.swing.JCheckBox cbCaffeine;
    private javax.swing.JComboBox<String> cbListSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listDrinkList;
    private javax.swing.JList<String> listType;
    // End of variables declaration//GEN-END:variables
}
